apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-voice

resources:
  - namespace.yaml
  - config/configmap.yaml
  - config/secrets.yaml
  - data/postgres-statefulset.yaml
  - data/redis-deployment.yaml
  - data/minio-deployment.yaml
  - api/deployment.yaml
  - api/service.yaml
  - portal/deployment.yaml
  - portal/service.yaml
  - portal/ingress.yaml
  - voice/deployment.yaml
  - voice/service.yaml
